name: huawei_location_example
description: Demonstrates how to use the Huawei Location plugin.

environment:
  sdk: '>=2.14.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.0
  huawei_location:
    path: ../
  permission_handler:
    path: /Users/better/dev/flutter_permission_handler/permission_handler


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
